### ISSUE TITLE
forum in php

### ISSUE THREAD

**Issue by theharshil** [conmarap/WP8-Speech-Recognition#1]
i want to create chat forum in php which include  following functionality
1. student can post que and teacher can answer that que
now my problem is more than 1 teacher can answer many que 
so how to implement this 
in project i have create 1 php file which so list of que .
here i want to implement ,when user click on that que new page open in tab and show list of answer 
how to do this  ?

**Comment by conmarap** [comment]
I don't think this is the correct place to ask that question. Regardless, the idea goes like this:

1. Create a database.
2. Create a table for the questions that have 
 * An id
 * A creator
 * A teacher that can answer
3. Create a PHP script that retrieves all that data and, then,
4. the front-end to show all the information.

There are a lot of tutorials online on how to do this stuff. Good luck.
